### ISSUE TITLE
Concern for reentrancy in depositCollateral function

### ISSUE THREAD

**Issue by syed-ghufran-hassan** [etherfi-protocol/cash-contracts#40]
The function is not adhering to CEI pattern so I propose the following CEI pattern.

```solidity
function depositCollateral(
    address token,
    address user,
    uint256 amount
) external {
    if (!isCollateralToken(token)) revert UnsupportedCollateralToken();

    // Effects: Update state before interacting with external contracts
    _totalCollateralAmounts[token] += amount;
    _userCollateral[user][token] += amount;

    // Interactions: Perform the external call after state updates
    IERC20(token).safeTransferFrom(msg.sender, address(this), amount);

    emit DepositedCollateral(msg.sender, user, token, amount);
}
```

The purpose was to eliminate reentrancy attack and address state inconsistencies

**Comment by shivam-ef** [comment]
Can you please add an example to show how it can be reentered?

**Comment by syed-ghufran-hassan** [comment]
If the state updates (_totalCollateralAmounts and _userCollateral) were made after the safeTransferFrom call, an attacker could potentially re-enter the function before the state is updated, leading to inconsistent state.

**Comment by shivam-ef** [comment]
We already have reentrancy guard on the deposit collateral function. Check here:
https://github.com/etherfi-protocol/cash-contracts/blob/main/src/debt-manager/DebtManagerCore.sol#L431
